sudo: false
language: node_js
node_js:
  - "6"
services:
  - mongodb
install:
  - npm install --no-optional
before_script:
  - sleep 15
script:
  - ./node_modules/.bin/grunt eslint-test-no-activiti-coverage
